default['mysql']['repository'] = "mysql-community-release-el6-7.noarch.rpm"
default['mysql']['db_host'] = "localhost"
default['mysql']['charset'] = "utf8"
default['mysql']['collate'] = "utf8_general_ci"
default['mysql']['my_cnf'] = "/etc/my.cnf"
